import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Search from '../components/Search'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Meal Gen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<main>
				<Search />
			</main>
    </div>
  )
}

export default Home
